# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FYbvfPjszf5xFb96j38eVVVZsM2H-uj
"""

# initilialization for sympy utilization

from sympy import * 
x , y , z = symbols('x,y,z')
init_printing(use_unicode=True)

diff(cos(x) , x)

diff(exp(x**2) , x) #exp() is a inbuild func in py

expr = exp(x*y*z)
diff(expr , x , y ,y , z, z, z, z)

m , n , a , b = symbols('m n a b')
expr = (a*x +b)**m
expr.diff(x,n)

integrate(cos(x) , x)

integrate(exp(-x), (x , 0 , oo))

integ = Integral(sin(x**2), x)
integ

integ.doit() # call doit as a func



